const actionTypes = {
  // homeReducer action type
  GET_BANNER: "GET_BANNER",

  // music action type
  SET_CURRENT_SONG_ID: "SET_CURRENT_SONG_ID",
  SET_PLAY_AUDIO: "SET_PLAY_AUDIO",
  SET_LIST_SONG: "SET_LIST_SONG",
  SET_ALBUM: "SET_ALBUM",
  SET_CURRENT_SONG_DATA: "SET_CURRENT_SONG_DATA",
  SET_CURRENT_ALBUM_DATA: "SET_CURRENT_ALBUM_DATA",
  SET_POSTION_MOUSE: "SET_POSTION_MOUSE",
  SET_PLAYLIST_DATA: "SET_PLAYLIST_DATA",
  SET_RECENLY_DATA: "SET_RECENLY_DATA",
  SET_SEARCH_DATA: "SET_SEARCH_DATA",

  // controlSize
  SET_DOM_PAGE: "SET_DOM_PAGE",
  SET_DOM_RIGHT_SIDE_BAR: "SET_DOM_RIGHT_SIDE_BAR",

  // themes
  SET_CHANGE_THEME_BLUE: "SET_CHANGE_THEME_BLUE",
  SET_CHANGE_THEME_PINK: "SET_CHANGE_THEME_PINK",

  // Modal
  SET_MODAL_CHANGE_THEMES: "SET_MODAL_CHANGE_THEMES:",
  SET_MODAL_AUTH: "SET_MODAL_AUTH",
};

export default actionTypes;
